apiVersion: v1
kind: Service
metadata:
  name: web-service-grupo-x
  namespace: projeto-grupo-x
spec:
  type: NodePort
  selector:
    app: web-projeto-grupo-x
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
